### ISSUE TITLE
no matching function for call to 'Adafruit_BME280::Adafruit_BME280(int, int)'

### ISSUE THREAD

**Issue by skipperearly** [Takatsuki0204/BME280-I2C-ESP32#2]

**Comment by tobozo** [comment]
overwrite your existing files in the arduino/libraries/Adafruit_BME280 folder

**Comment by Sawadee2u** [comment]
Getting the exact call error for this project:
(
http://educ8s.tv/esp32-weather-station)
Refreshing library did not help.
