### ISSUE TITLE
Fails on Lolin OLED boards (ESP32+OLED)

### ISSUE THREAD

**Issue by skitsanos** [Takatsuki0204/BME280-I2C-ESP32#3]
Hi,

It does work perfectly on usual ESP32 boards, but it fails on the ones with OLED display on it, like this one: [https://www.aliexpress.com/item/Lolin-ESP32-wemos-ESP32-WiFi-Modules-Bluetooth-Dual-ESP-32-ESP-32S-ESP8266/32807483723.html](https://www.aliexpress.com/item/Lolin-ESP32-wemos-ESP32-WiFi-Modules-Bluetooth-Dual-ESP-32-ESP-32S-ESP8266/32807483723.html) 

So after display.init() was called, i can't 'see' the BME sensor attached...

Once my code reaches here:

```
bool bme_status = bme.begin(BME280_ADDRESS);
  if (!bme_status) {
    Serial.println("Could not find a valid BME280 sensor, check wiring!");
    while (1);
  }
```

bme can't proceed... seems can't detect it...

**Comment by tobozo** [comment]
have you edited the pins assignment in the example ?

Lolin board uses pins 5/4 as SDA/SCL

```
#define I2C_SDA 5
#define I2C_SCL 4
```
